-- DATA CLEANING PROCCESS
-- FINDING DUPLICATES IN THE DATASET

-- CHECKING DUPLICATE ZIP CODE
SELECT
customer_name,
zip_code,
COUNT(*) AS count
FROM customers
GROUP BY 1,2
HAVING COUNT(*) > 1

-- CHECKING DUPLICATE HOME ADDRESS
SELECT
customer_name,
home_address,
COUNT(*) AS count
FROM customers
GROUP BY 1,2
HAVING COUNT(*) > 1

-- CHECKING DUPLICATE CITY
SELECT
customer_name,
city,
COUNT(*) AS count
FROM customers
GROUP BY 1,2
HAVING COUNT(*) > 1

-- CHECKING DUPLICATE STATE
SELECT
customer_name,
state,
COUNT(*) AS count
FROM customers
GROUP BY 1,2
HAVING COUNT(*) > 1

-- CHECKING DUPLICATE COUNTRY
SELECT
customer_name,
country,
COUNT(*) AS count
FROM customers
GROUP BY 1,2
HAVING COUNT(*) > 1

-- CUSTOMER TABLE IS FREE OF DUPLICATES
-- ORDERS TABLE HAVE NO CATEGORICAL COLUMN
-- PRODUCT TABLE HAVE NO CATEGORICAL COLUMN
-- SALES TABLE HAVE NO CATEGORICAL COLUMN

